### ISSUE TITLE
Add more fields inherited IntField

### ISSUE THREAD

**Issue by moreal** [moreal/pystructs#11]
Now, there are only two fields, `Int32Field` and `Int64Field`, as alias of `IntField(size=<n>)`.

But fields like Int8, Int16 are needed when we write struct code :crying_cat_face:

**Comment by MartinRakacolli** [comment]
I'm willing to help with this issue.

**Comment by moreal** [comment]
Hello, @MartinRakacolli   

First, Thank you for your interest in the `pystructs` project.  
But, there isn't contributing guide yet. Have you ever contributed to an open source project?

**Comment by MartinRakacolli** [comment]
No, I haven't. I just downloaded the files and made changes to them directly.

**Comment by moreal** [comment]
Okay, @MartinRakacolli then I'll give you a simple sequence.

1. Fork this repository
2. Clone your repository
3. Make changes about this issue
4. Commit and push to your repository
5. Make `Pull Request` , then I will review the code for you :+1: 

If you' have any question about this process, feel free to ask :grin:

**Comment by MartinRakacolli** [comment]
Alright, I think I did it correctly.

**Comment by moreal** [comment]
@MartinRakacolli Ok, Then can you make pull-request?

**Comment by MartinRakacolli** [comment]
I think I just made it. Did I do that correctly?

**Comment by moreal** [comment]
@MartinRakacolli Yes!  you did :grin:

I will review and remain comments to edit, soon :+1:

**Comment by moreal** [comment]
This issue is resolved by #12

**Comment by moreal** [comment]
This issue is resolved by #12
